---
- name: yum update
  yum:
    name: '*'
    state: latest

- name: disable selinux
  selinux:
    state: disabled

- name: reboot
  shell: "sleep 2 && reboot"
  async: 1
  poll: 0

- name: wait rebooting
  local_action: wait_for host={{ inventory_hostname }} port=22 delay=30
  become: no

- name: disable firewalld
  systemd:
    name: firewalld.service
    enabled: no
    state: stopped
- name: install docker
  yum:
    name: '{{ item }}'
  with_items:
    - device-mapper-persistent-data
    - lvm2

- name: add docker yum repository
  yum_repository:
    include: https://download.docker.com/linux/centos/docker-ce.repo

- name: install docker
  yum:
    name: docker-ce-17.03.3.ce

- name: start and enable docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: add kubernetes yum repository
  yum_repository:
    name: Kubernetes
    description: kubernetes yum repository
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: update yum
  yum:
    name: '*'
    state: latest

- name: install kubeadm, kubelet and kubectl
  yum:
    name: '{{ item }}'
    state: installed
  with_items:
    - kubelet
    - kubeadm
    - kubectl

- name: put /etc/hosts
  template:
    src: templates/hosts.j2
    dest: /etc/hosts

- name: put sysctl config
  copy:
    src: files/k8s.conf
    dest: /etc/sysctl.d/k8s.conf

- name: sysctl update
  command: sysctl --system

- name: turn off swap
  command: swapoff -a

- name: disable swap
  lineinfile:
    path: /etc/fstab
    regexp: '^(.*swap.*)'
    line: '#\1'
    backrefs: yes

- name: start and enable kubelet
  systemd:
    name: kubelet.service
    enabled: yes
    state: started
