---
- name: yum update
  yum:
    name: '*'
    state: latest

- name: disable selinux
  selinux:
    state: disabled

- name: reboot
  shell: "sleep 2 && reboot"
  async: 1
  poll: 0

- name: wait rebooting
  local_action: wait_for host={{ inventory_hostname }} port=22 delay=30
  become: no

- name: disable firewalld
  systemd:
    name: firewalld.service
    enabled: no
    state: stopped
- name: install docker
  yum:
    name: '{{ item }}'
  with_items:
    - device-mapper-persistent-data
    - lvm2

- name: add docker yum repository
  yum_repository:
    baseurl: '{{ item.baseurl }}'
    description: '{{ item.description }}'
    enabled: '{{ item.enabled }}'
    gpgcheck: '{{ item.gpgcheck }}'
    gpgkey: '{{ item.gpgkey }}'
    name: '{{ item.name }}'
  with_items:
    - name: docker-ce-stable
      description: Docker CE Stable - $basearch
      baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
      enabled: true
      gpgcheck: true
      gpgkey: https://download.docker.com/linux/centos/gpg
    - name: docker-ce-stable-debuginfo
      description: Docker CE Stable - Debuginfo $basearch
      baseurl: https://download.docker.com/linux/centos/7/debug-$basearch/stable
      enabled: false
      gpgcheck: true
      gpgkey: https://download.docker.com/linux/centos/gpg
    - name: docker-ce-stable-source
      description: Docker CE Stable - Sources
      baseurl: https://download.docker.com/linux/centos/7/source/stable
      enabled: true
      gpgcheck: true
      gpgkey: https://download.docker.com/linux/centos/gpg
    - name: docker-ce-edge
      description: Docker CE Edge - $basearch
      baseurl: https://download.docker.com/linux/centos/7/$basearch/edge
      enabled: false
      gpgcheck: true
      gpgkey: https://download.docker.com/linux/centos/gpg
    - name: docker-ce-edge-debuginfo
      description: Docker CE Edge - Debuginfo $basearch
      baseurl: https://download.docker.com/linux/centos/7/debug-$basearch/edge
      enabled: false
      gpgcheck: true
      gpgkey: https://download.docker.com/linux/centos/gpg
    - name: docker-ce-edge-source
      description: Docker CE Edge - Sources
      baseurl: https://download.docker.com/linux/centos/7/source/edge
      enabled: false
      gpgcheck: true
      gpgkey: https://download.docker.com/linux/centos/gpg
    - name: docker-ce-test
      description: Docker CE Test - $basearch
      baseurl: https://download.docker.com/linux/centos/7/$basearch/test
      enabled: false
      gpgcheck: true
      gpgkey: https://download.docker.com/linux/centos/gpg
    - name: docker-ce-test-debuginfo
      description: Docker CE Test - Debuginfo $basearch
      baseurl: https://download.docker.com/linux/centos/7/debug-$basearch/test
      enabled: false
      gpgcheck: true
      gpgkey: https://download.docker.com/linux/centos/gpg
    - name: docker-ce-test-source
      description: Docker CE Test - Sources
      baseurl: https://download.docker.com/linux/centos/7/source/test
      enabled: false
      gpgcheck: true
      gpgkey: https://download.docker.com/linux/centos/gpg
    - name: docker-ce-nightly
      description: Docker CE Nightly - $basearch
      baseurl: https://download.docker.com/linux/centos/7/$basearch/nightly
      enabled: false
      gpgcheck: true
      gpgkey: https://download.docker.com/linux/centos/gpg
    - name: docker-ce-nightly-debuginfo
      description: Docker CE Nightly - Debuginfo $basearch
      baseurl: https://download.docker.com/linux/centos/7/debug-$basearch/nightly
      enabled: false
      gpgcheck: true
      gpgkey: https://download.docker.com/linux/centos/gpg
    - name: docker-ce-nightly-source
      description: Docker CE Nightly - Sources
      baseurl: https://download.docker.com/linux/centos/7/source/nightly
      enabled: false
      gpgcheck: true
      gpgkey: https://download.docker.com/linux/centos/gpg


- name: install docker
  yum:
    name: docker-ce-17.03.3.ce

- name: start and enable docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: add kubernetes yum repository
  yum_repository:
    name: Kubernetes
    description: kubernetes yum repository
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: update yum
  yum:
    name: '*'
    state: latest

- name: install kubeadm, kubelet and kubectl
  yum:
    name: '{{ item }}'
    state: installed
  with_items:
    - kubelet
    - kubeadm
    - kubectl

- name: put /etc/hosts
  template:
    src: templates/hosts.j2
    dest: /etc/hosts

- name: put sysctl config
  copy:
    src: files/k8s.conf
    dest: /etc/sysctl.d/k8s.conf

- name: sysctl update
  command: sysctl --system

- name: turn off swap
  command: swapoff -a

- name: disable swap
  lineinfile:
    path: /etc/fstab
    regexp: '^(.*swap.*)'
    line: '#\1'
    backrefs: yes

- name: start and enable kubelet
  systemd:
    name: kubelet.service
    enabled: yes
    state: started
