---
- name: configure cgroup driver
  replace:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: cgroup-driver=systemd
    replace: cgroup-driver=cgroupfs

- name: restart kubelet
  systemd:
    name: kubelet
    daemon-reload: yes
    state: restarted

- name: initialize for calico
  shell: kubeadm init --pod-network-cidr=192.168.0.0/16 | tail -n2 | head -n1 | awk '{print $7;}'
  register: kubeadm_hash
  when: network_plugin == 'calico'

- name: initialize for canal
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 | tail -n2 | head -n1 | awk '{print $7;}'
  register: kubeadm_hash
  when: network_plugin == 'canal'

- name: initialize for flannel
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 | tail -n2 | head -n1 | awk '{print $7;}'
  register: kubeadm_hash
  when: network_plugin == 'flannel'

- name: get token
  shell: kubeadm token list | tail -n 1 | awk '{print $1;}'
  register: kubeadm_token

- name: configure bridge
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present

- name: install pod network
  command: kubectl --kubeconfig=/etc/kubernetes/admin.conf apply -f https://raw.githubusercontent.com/coreos/flannel/v0.9.0/Documentation/kube-flannel.yml

- name: register config to var
  command: cat /etc/kubernetes/admin.conf
  register: configure

- name: show config
  debug:
    msg: "{{ configure.stdout }}"

- name: add kubeconfig to bashrc
  lineinfile:
    path: /root/.bashrc
    line: "export KUBECONFIG=/etc/kubernetes/admin.conf"
